#!/usr/bin/python
import sys
import os
sys.path.append(sys.path[0]+'/files/')
from File import *
from Plot import *
import matplotlib.pyplot as mpl

def showDescription():
   print "Create a meteogram for a COMPS Netcdf output file\n"
   print "usage: meteo.py file [location] [-f imagefile]\n"
   print "Arguments:"
   print "   file:         Filename of COMPS file in NetCDF format"
   print "   location:     Draw meteogram for this location index"
   print "   imagefile:    Save image to this filename"

if(len(sys.argv) == 1):
   showDescription()
   sys.exit()

ifile = None
location = None
ofile = None

# Read command line arguments
i = 1
while(i < len(sys.argv)):
   arg = sys.argv[i]
   if(arg[0] == '-'):
      # Process option
      if(arg == "-f"):
         ofile = sys.argv[i+1]
      i = i + 1
   else:
      if(ifile == None):
         ifile = sys.argv[i]
      elif(location == None):
         location = int(sys.argv[i])
   i = i + 1

if(ifile == None):
   print "Needs input file"

file = NetCdfFile(ifile,location=location)
pl = CdfPlot(file)

pl.plot(mpl.gca())
#mpl.subplots_adjust(left=0, bottom=0, right=1, top=1, wspace=None, hspace=None)

if(ofile != None):
   mpl.savefig(ofile, bbox_inches='tight')
else:
   fig = mpl.gcf()
   fig.canvas.set_window_title(ifile)
   mpl.show()
