#!/bin/csh
echo "Downloading gfsOp"
set gribFolder = input/gfs
if($1 == "") then
   echo "download: Missing date"
   exit 1
endif

# Create data directory
if(!(-f data)) then
   mkdir data
endif

set yyyymmdd = $1

# Check if file is already there
set file = "data/${yyyymmdd}.nc"
if(-e $file) then
   echo "File $file is already there"
   exit 0
endif


cd ../../$gribFolder
./download $yyyymmdd

cd ../../
if(!(-e convert.exe)) then
   "Please compile convert.exe"
   exit 2;
endif
./convert.exe $yyyymmdd -in=gfs -dim=gfsOp -out=gfsOp

# Create sample file link
if(!(-f sample.nc)) then
   ln -s data/$yyyymmdd.nc sample.nc
endif
