#!/usr/bin/python
import sys
import os
sys.path.append(sys.path[0] + '/files/')
from VerifFile import *
from VerifPlot import *
from VerifData import *
from Common import *
import matplotlib.pyplot as mpl
import textwrap


pl = BaseRatePlot(thresholds, binned=binned)
